{% set name = "e3sm_to_cmip" %}
{% set version = "1.13.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cmor >=3.7.0
    - dask
    - nco >=5.1.4
    - netcdf4
    - numpy >=2.0.0,<3.0.0
    - pyyaml
    - tqdm
    - xarray >=2024.03.0
    - xcdat >=0.8.0

test:
  requires:
    - python {{ python_min }}
  commands:
    - e3sm_to_cmip --help
  imports:
    - e3sm_to_cmip

about:
  home: https://github.com/E3SM-Project/e3sm_to_cmip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A cli utility to transform E3SM model output into CMIP compatible data.
  description: |
    Transform e3sm time series variables into cmip compatible data. Each
    variable needs its own handler script, implemented in the cmor_handlers
    directory (see directory for current handlers). In addition, you will need
    to clone the cmor repo (https://github.com/PCMDI/cmor) to access the Test
    and Tables directories. Test holds the common_user_input.json file which
    can be used as a placeholder for the user supplied metadata, and Tables
    holds all the CMIP6 variable tables.
  doc_url: https://github.com/E3SM-Project/e3sm_to_cmip
  dev_url: https://github.com/E3SM-Project/e3sm_to_cmip

extra:
  recipe-maintainers:
    - xylar
    - tomvothecoder
    - chengzhuzhang